In [19]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import re
import pandas as pd
import time

In [2]:
# 구글맵에서 을지로3가 식당이라는 키워드로 검색한 페이지를 url로 가져온다
url = "https://www.google.com/maps/search/%EC%9D%84%EC%A7%80%EB%A1%9C3%EA%B0%80+%EC%8B%9D%EB%8B%B9/@37.5662637,126.9902297,17z/data=!3m1!4b1!4m2!2m1!6e5?hl=ko"
driver = webdriver.Chrome()
driver.get(url)

In [3]:
# 식당이름과 정보가 나와있는 박스를 선택하여 elem 이라는 변수에 저장한다.
elem = driver.find_element_by_xpath("""//*[@id="pane"]/div/div[1]/div""")

In [4]:
elem

In [108]:
# 각 식당이름을 가져오려고 하는데, 일괄된 코드로 가져올 수 없어서 이렇게 div[%s]해서 가져옴
# div[3], div[5], div[7] ... 이런식으로 바꾸어주어야 가져올 수 있음
# while문을 쓴 이유는 해당 페이지에 음식점이 몇 개인지 모르기 때문에 for문으로 범위를 지정할 수 없었음.
# 또한 첫번째 xpath는 박스 안에 있는 내용을 전부 가져오고, 그 밑 부분에 식당 이름만 나온 부분을 지정하여 xpath로 또가져옴.
# 이 과정에서 식당이름만 나오는 두 번째 data 선언 부분도 계속해서 div[5], div[7]등으로 바뀌어가며 찾아와야함. 위 첫번째 data의 i와 같음.
#list_all = []
i = 1
while True :                               
    try :                                   
        data = elem.find_element_by_xpath('//*[@id="pane"]/div/div[1]/div/div/div[4]/div[1]/div[%s]/div[1]/div[1]/div[1]/div[1]/div[2]/h3/span' %(i))
        print(data.text)
        list_all.append(data.text)
        i += 2
    except :
        print('다음페이지로 가세요')
        break

고향식당
우화식당
대지 식당
코요테살룬
다음페이지로 가세요

In [100]:
# 다음페이지 가기 
elem.find_element_by_xpath('//*[@id="n7lv7yjyC35__section-pagination-button-next"]/span').click()

In [109]:
print(list_all)
len(list_all)

['을지식당', '은성장', '세진식당', '을지오뎅', '조선옥', '동원집', '안동장', '통일집', '골목식당', '양미옥', '청와옥 을지로3가직영점', '을지면옥', '삼곱식당 을지로점', '산수갑산', '을지수제비', '오구반점', '을지로 장만옥', '원조녹두', '이모네 영양돌솥', '취향로3가 (Bar Chroad3)', '전주집', '을지로 양대장', '문경식당', '동경우동 충무로점', '동경우동 을지로3가점', '사랑방칼국수', '을지손칼국수', '도이농 소고기 쌀국수', '풍남골뱅이', '각시어멍네', '호성', '옛날농장 을지로3가점', '을지육점', '을삼골뱅이', '만선호프3', '유숙단부자낙지', '그랑블루 을지로', '전주옥', '원조영락골뱅이', '종로생삼겹살', '경일옥 핏제리아', '원조 호남식당', '을지로미팅룸', '3가식당', '한국관', '산과들그리고바다', '두꺼비식당', '만선호프', '을지깐깐(Eulji Canh Canh)', '줄리아', '삼가식당', '둘둘치킨 을지로3가점', '마포쭈꾸미', '빨간우체통', '북창동 김치찌개 삼겹살', '을지분식 (Eulji Bunsik)', '성옥', '문스타파 을지로점', '을지로골뱅이 거리', '을지맥옥', '호참치', '촙촙', '을지칼국수', 'The Edge', '닭한마리', '이남장 을지로본점', '경일옥', '을지로 석(碩) 도 너는', 'MMMIO CAFE', '청시행', '명인돈까스', '우촌돌솥설렁탕', '해태스낵', '더랜치브루잉 을지로', '을지빈 (Euljibean)', '골목집', '행복한 돈까스&분식', 'ドンウォンチプ', '복어이야기', '황평집 닭곰탕', '바오차이', '평래옥', '김가네김밥 을지로3가점', '남원추어탕', '비앤비펍앤레스토랑', '을지 OB 베어', '화덕과 베토벤', '끽비어 컴퍼니', 'Moon’s Tapas', '다원닭한마리빈대떡', '을지로코이', '바스버거 을지로점', '커피한약방 을지로점', '독일분식', '다케오 호르몬 데판야끼', '오카구라', '다선', '전주옥', '우일집', '영빈각', '동강나루터', '상해', '을지로제', '산불등심', '엉뚱한국수', '신씨화로 무교다동점', '우래옥', '오븐에빠진닭', '쿄다이', '곤지암소머리국밥', '계림식당 (계림닭도리탕)', '육일봉', '원조갈매기집', '석산정', '육전식당 5호점', '호텔수선화 Hotel Soosunhwa', 'Bas burger eljiro', '박가네털랭이메기매운탕', '영덕막회', '호반집', '부타이 제2막', '르템플', '대원식당', '이모분식', '미스터빠삭', '꽃지로', '녁', '다전식당', '을지삼계탕', '물결', '을지로 노가리골목', '장수 삼계탕', '레드스타', '대원집', '한라활어랑참치', '수정식당', '황소고집', 'Bier Halle', '작은물', '한시락', '고향식당', '우화식당', '대지 식당', '코요테살룬']

144

In [110]:
list_all_1 = list_all.copy()

In [106]:
list_all = list_all_1

In [117]:
list_all

['을지식당',
 '은성장',
 '세진식당',
 '을지오뎅',
 '조선옥',
 '동원집',
 '안동장',
 '통일집',
 '골목식당',
 '양미옥',
 '청와옥 을지로3가직영점',
 '을지면옥',
 '삼곱식당 을지로점',
 '산수갑산',
 '을지수제비',
 '오구반점',
 '을지로 장만옥',
 '원조녹두',
 '이모네 영양돌솥',
 '취향로3가 (Bar Chroad3)',
 '전주집',
 '을지로 양대장',
 '문경식당',
 '동경우동 충무로점',
 '동경우동 을지로3가점',
 '사랑방칼국수',
 '을지손칼국수',
 '도이농 소고기 쌀국수',
 '풍남골뱅이',
 '각시어멍네',
 '호성',
 '옛날농장 을지로3가점',
 '을지육점',
 '을삼골뱅이',
 '만선호프3',
 '유숙단부자낙지',
 '그랑블루 을지로',
 '전주옥',
 '원조영락골뱅이',
 '종로생삼겹살',
 '경일옥 핏제리아',
 '원조 호남식당',
 '을지로미팅룸',
 '3가식당',
 '한국관',
 '산과들그리고바다',
 '두꺼비식당',
 '만선호프',
 '을지깐깐(Eulji Canh Canh)',
 '줄리아',
 '삼가식당',
 '둘둘치킨 을지로3가점',
 '마포쭈꾸미',
 '빨간우체통',
 '북창동 김치찌개 삼겹살',
 '을지분식 (Eulji Bunsik)',
 '성옥',
 '문스타파 을지로점',
 '을지로골뱅이 거리',
 '을지맥옥',
 '호참치',
 '촙촙',
 '을지칼국수',
 'The Edge',
 '닭한마리',
 '이남장 을지로본점',
 '경일옥',
 '을지로 석(碩) 도 너는',
 'MMMIO CAFE',
 '청시행',
 '명인돈까스',
 '우촌돌솥설렁탕',
 '해태스낵',
 '더랜치브루잉 을지로',
 '을지빈 (Euljibean)',
 '골목집',
 '행복한 돈까스&분식',
 'ドンウォンチプ',
 '복어이야기',
 '황평집 닭곰탕',
 '바오차이',
 '평래옥',
 '김가네김밥 을지로3가점',
 '남원추어탕',
 '비앤비펍앤레스토랑',
 '을지 OB 베어',
 '화덕과 베토벤',
 '끽비어 컴퍼니',
 'Moon’s Tapas',
 '다원닭한마리빈대떡',
 '을지로코이',
 '바스버거 을지로점',
 '커피한약방 을지로점',
 '독일분식',
 '다케오 호르몬 데판야끼',
 '오카구라',
 '다선',
 '전주옥',
 '우일집',
 '영빈각',
 '동강나루터',
 '상해',
 '을지로제',
 '산불등심',
 '엉뚱한국수',
 '신씨화로 무교다동점',
 '우래옥',
 '오븐에빠진닭',
 '쿄다이',
 '곤지암소머리국밥',
 '계림식당 (계림닭도리탕)',
 '육일봉',
 '원조갈매기집',
 '석산정',
 '육전식당 5호점',
 '호텔수선화 Hotel Soosunhwa',
 'Bas burger eljiro',
 '박가네털랭이메기매운탕',
 '영덕막회',
 '호반집',
 '부타이 제2막',
 '르템플',
 '대원식당',
 '이모분식',
 '미스터빠삭',
 '꽃지로',
 '녁',
 '다전식당',
 '을지삼계탕',
 '물결',
 '을지로 노가리골목',
 '장수 삼계탕',
 '레드스타',
 '대원집',
 '한라활어랑참치',
 '수정식당',
 '황소고집',
 'Bier Halle',
 '작은물',
 '한시락',
 '고향식당',
 '우화식당',
 '대지 식당',
 '코요테살룬']

In [119]:
all_food_list = pd.DataFrame(list_all)

In [120]:
all_food_list

         0
0     을지식당
1      은성장
2     세진식당
3     을지오뎅
4      조선옥
..     ...
139    한시락
140   고향식당
141   우화식당
142  대지 식당
143  코요테살룬

[144 rows x 1 columns]

In [121]:
all_food_list.to_csv('all_food_list.csv')

In [134]:
# cafe_all = []
i = 1
while True :                               
    try :                                   
        data = elem.find_element_by_xpath('//*[@id="pane"]/div/div[1]/div/div/div[4]/div[1]/div[%s]/div[1]/div[1]/div[1]/div[1]/div[2]/h3/span' %(i))
        print(data.text)
        cafe_all.append(data.text)
        i += 2
    except :
        print('다음페이지로 가세요')
        break

Starbucks
4F Cafe
카페 코인
최씨네목공소
다음페이지로 가세요

In [135]:
print(cafe_all)
len(cafe_all)

['호텔수선화 Hotel Soosunhwa', '커피한약방 을지로점', '잔', '분카샤', '쎄투', '물결', '혜민당', '을지빈 (Euljibean)', '작은물', '세투', '이디야 을지로 3가점', '죠지 서울', '호랑이', '을지로맨틱', '탐앤탐스 을지로3가점', '하이데어', 'twoffice (투피스)', '커피사 마리아', '원커피숍', '커피인쇄소', '스트라다로스터즈', '허스키커피', '을지로3가', 'MMMIOCAFE', '미스아메리카노', '앙가주망', 'mwm', '카페 클래직', "O'brett", '챔프커피 제3작업실', '청와옥 을지로3가직영점', '노아스로스팅 을지로점', '할리스커피 을지로입구점', '스타벅스중구저동점', '육일봉', 'MMMIO CAFE', '커피가좋아3s', '서울라이트', '스타사주카페', '할리스커피 동대문역사문화공원점', 'Starbucks', '4F Cafe', '카페 코인', '최씨네목공소']

44

In [136]:
cafe_all = pd.DataFrame(cafe_all)

In [137]:
cafe_all

                        0
0   호텔수선화 Hotel Soosunhwa
1              커피한약방 을지로점
2                       잔
3                     분카샤
4                      쎄투
5                      물결
6                     혜민당
7         을지빈 (Euljibean)
8                     작은물
9                      세투
10            이디야 을지로 3가점
11                  죠지 서울
12                    호랑이
13                  을지로맨틱
14            탐앤탐스 을지로3가점
15                   하이데어
16         twoffice (투피스)
17                커피사 마리아
18                   원커피숍
19                  커피인쇄소
20               스트라다로스터즈
21                  허스키커피
22                  을지로3가
23              MMMIOCAFE
24                미스아메리카노
25                   앙가주망
26                    mwm
27                 카페 클래직
28                O'brett
29             챔프커피 제3작업실
30           청와옥 을지로3가직영점
31            노아스로스팅 을지로점
32           할리스커피 을지로입구점
33              스타벅스중구저동점
34                    육일봉
35             MMMIO CAFE
36                커피가좋아3s
37                  서울라이트
38                 스타사주카페
39       할리스커피 동대문역사문화공원점
40              Starbucks
41                4F Cafe
42                  카페 코인
43                 최씨네목공소

In [138]:
cafe_all.to_csv('cafe_all.csv')